rcar-gen3: optee-os: WORKAROUND for compile error with GCC 10.x
This commit disables "outline-atomics" flag to avoid the following
compile error:

|  aarch64-poky-linux-ld: ...aarch64-poky-linux/10.2.0/libgcc.a(lse-init.o): in function `init_have_lse_atomics':
| ...work-shared/gcc-10.2.0-r0/gcc-10.2.0/libgcc/config/aarch64/lse-init.c:44: undefined reference to `__getauxval'
| make: *** [core/arch/arm/plat-rcar/link.mk:39: out/arm-plat-rcar/core/all_objs.o] Error 1

Signed-off-by: Khang Nguyen <khang.nguyen.xw@renesas.com>
Change-Id: I7bf5ec0dcad1a654454faea09dbb8462bb9192c9
(cherry picked from commit 5ac0c86a45d7e433236fc9156104ba7c6306093f)