rcar-gen3: libglu: Fix missing header
This commit adds 'libegl' to 'DEPENDS' to fix missing header issue:

glext.h:56:10: fatal error: KHR/khrplatform.h: No such file or directory
|    56 | #include <KHR/khrplatform.h>
|       |          ^~~~~~~~~~~~~~~~~~~

Signed-off-by: Khang Nguyen <khang.nguyen.xw@renesas.com>
Change-Id: Iafb5dd5f9867802a343b6c2657317e219dc7c33c