rcar-gen3: kernel-module-qos: Fix compile error with kernel 5.4
Fix missing mod_devicetable.h issue:

| qos-module/files/qos/drv/qos_drv.c:186:34: error: array type has
incomplete element type 'struct of_device_id'
  186 | static const struct of_device_id qos_of_match[] = {
      |                                  ^~~~~~~~~~~~

Signed-off-by: Harunobu Kurokawa <harunobu.kurokawa.dn@renesas.com>
Signed-off-by: Khang Nguyen <khang.nguyen.xw@renesas.com>
Change-Id: Iaad7c5b7ba54d729d32369df4cb37ad31b86e1c4