rcar-gen3: linux-renesas: Fix perf compile error
libbfd has changed the bfd_section_* macros to inline functions
bfd_section_<field> since 2019-09-18. See below two commits:
  o http://www.sourceware.org/ml/gdb-cvs/2019-09/msg00064.html
  o https://www.sourceware.org/ml/gdb-cvs/2019-09/msg00072.html

This fix make perf able to build with both old and new libbfd.

| .../usr/src/debug/perf/1.0-r9/perf-1.0/tools/perf/util/srcline.c:151:
| undefined reference to `bfd_get_section_size'

This patch is backported from:
    https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git
    Commit ID: 0ada120c883d4f1f6aafd01cf0fbb10d8bbba015

Signed-off-by: Khang Nguyen <khang.nguyen.xw@renesas.com>
Change-Id: I16493b7d8d10acc80d2cdd936231d0e15a5da86c