rcar-gen3: gcc-runtime: Fix QA issues while upgrading to GCC Linaro v5.2
This patch is to fix the below error for GCC Linaro v5.2.
ERROR: QA Issue: gcc-runtime: Files/directories were installed but not shipped in any package:
  /usr/lib64/libstdc++fs.la
  /usr/lib64/libstdc++fs.a
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
gcc-runtime: 2 installed and not shipped files. [installed-vs-shipped]

libstdc++fs is a new file, which does not exist in GCC Linaro v5.1.

Signed-off-by: Thao Nguyen <thao.nguyen.yb@rvc.renesas.com>
Signed-off-by: Takeshi Saito <takeshi.saito.xv@renesas.com>