rcar-gen3: kernel-module-vspm: Add deploy/licenses into cleaned dir
When switch between different machines (i.e. salvator-x and h3ulcb),
we can meet below issue:

ERROR: kernel-module-vspm-1.0-r0 do_populate_lic: The recipe kernel-module-vspm is trying to install files into a shared area when those files already exist.
 Those files and their manifest location are:
  /ssd/FS_YP2.4/build_mmp/h3ulcb-build/tmp/deploy/licenses/kernel-module-vspm/generic_MIT
    (matched in manifest-salvator_x-kernel-module-vspm.populate_lic)
  /ssd/FS_YP2.4/build_mmp/h3ulcb-build/tmp/deploy/licenses/kernel-module-vspm/recipeinfo
    (matched in manifest-salvator_x-kernel-module-vspm.populate_lic)
  /ssd/FS_YP2.4/build_mmp/h3ulcb-build/tmp/deploy/licenses/kernel-module-vspm/GPL-COPYING
    (matched in manifest-salvator_x-kernel-module-vspm.populate_lic)
  /ssd/FS_YP2.4/build_mmp/h3ulcb-build/tmp/deploy/licenses/kernel-module-vspm/MIT-COPYING
    (matched in manifest-salvator_x-kernel-module-vspm.populate_lic)
  /ssd/FS_YP2.4/build_mmp/h3ulcb-build/tmp/deploy/licenses/kernel-module-vspm/generic_GPLv2
    (matched in manifest-salvator_x-kernel-module-vspm.populate_lic)
Please verify which recipe should provide the above files.

The reason is the tmp/deploy/licenses/kernel-module-vspm/ has not
been cleaned during do_clean task. To avoid it,
we should also clean ${LICENSE_DIRECTORY}/${PN} in do_clean.

Signed-off-by: Thao Nguyen <thao.nguyen.yb@renesas.com>
Signed-off-by: Thuy Tran <thuy.tran.xh@rvc.renesas.com>
Signed-off-by: Takamitsu Honda <takamitsu.honda.pv@renesas.com>