rcar-gen3: linuxptp: Fix compile error
This commit adds option to CFLAGS to fix the following compile error:

| In file included from clock.c:34:
| missing.h:59:2: error: redeclaration of enumerator 'HWTSTAMP_TX_ONESTEP_P2P'
|    59 |  HWTSTAMP_TX_ONESTEP_P2P = 3,
|       |  ^~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Khang Nguyen <khang.nguyen.xw@renesas.com>
Change-Id: If0098664e934eb80dbc4d292579591e7c200abcc
(cherry picked from commit 1139f2c1b1e6607bc381918991caa02c787bbb6e)