rcar-gen3: adsp-if-module: WORKAROUND to fix compile error with GCC 8.x
Current ADSP source code will get compilation error with GCC 8.x due
to new command-line option -Wpacked-not-aligned have been added
for the C and C++ compilers.

| In file included from ./include/xf-ap.h:46, from proxy/xf-proxy.c:26:
| ./include/xf-ap-msg.h:128:1: error: alignment 1 of 'struct xf_ext_param_msg' is less than 4 [-Werror=packed-not-ali| gned]
| }   __attribute__ ((__packed__)) xf_ext_param_msg_t;
| ^
| In file included from ./include/xf-ap.h:46, from proxy/xf-trace.c:20:
| ./include/xf-ap-msg.h:128:1: error: alignment 1 of 'struct xf_ext_param_msg' is less than 4 [-Werror=packed-not-ali| gned]
| }   __attribute__ ((__packed__)) xf_ext_param_msg_t;
| ^

This commit silenced -Wpacked-not-aligned errors when compiling
this ADSP module.

Signed-off-by: Thuy Tran <thuy.tran.xh@renesas.com>
Signed-off-by: Takamitsu Honda <takamitsu.honda.pv@renesas.com>