rcar-gen3: kernel-module-mmngr: Fix compile error with Kernel 5.4
This commit applies a patch to fix the following error:

| mmngr_drv/mmngr/mmngr-module/files/mmngr/drv/mmngr_drv.c:994:49: error:
| macro "access_ok" passed 3 arguments, but takes just 2
  994 |   if (!access_ok(VERIFY_WRITE, tmp, sizeof(*tmp))
      |                                                 ^

Signed-off-by: Harunobu Kurokawa <harunobu.kurokawa.dn@renesas.com>
Signed-off-by: Khang Nguyen <khang.nguyen.xw@renesas.com>
Change-Id: Id34a9a46b574c0430c071dcbd57213fe49ec07a5
(cherry picked from commit 87acdb5df61a5b6dbbc54236a13acc7baa29897e)