Rename linuxptp_2.0.bbappend
Corresponding recipe in meta-openembedded
was renamed to linuxptp_2.0.1.bb due to need to include
some security fixes. See for details:
openembedded/meta-openembedded@872e60a7

Change of name of original recipe resulted in yocto's error
```
 ERROR: No recipes available for:
  <local path>/meta-renesas/meta-rcar-gen3/recipes-connectivity/linuxptp/linuxptp_2.0.bbappend
```

This commit makes bbappend applicable to all 2.0, 2.0.1 and
other 2.* versions of original recipe.

Signed-off-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>