rcar-gen3: net-tools: Fix compile error when build with kernel 4.8 and 4.9
This commit backport the following commit from poky upstream:

commit 0f25619268d4eb4e4a40cac7cdb40de5bca9ade1
Author: Jackie Huang <jackie.huang@windriver.com>
Date:   Sun Oct 9 08:56:07 2016 +0800

    net-tools: fix building with linux-4.8

    Fix a build error when using the linux-4.8 headers that results
    in:

    In file included from
    .../sysroots/qemuarm64/usr/include/linux/if_tunnel.h:6:0,
                      from iptunnel.c:39:
    .../qemuarm64/usr/include/linux/ip.h:85:8: error: redefinition of
    'struct iphdr'
      struct iphdr {
             ^~~~~
    In file included from iptunnel.c:29:0:
    .../qemuarm64/usr/include/netinet/ip.h:44:8: note: originally
    defined here
      struct iphdr
             ^~~~~
    (From OE-Core rev: 94d15885c516e3bfee4fb68dfb568f4da6904052)

    Signed-off-by: Randy MacLeod <Randy.MacLeod@windriver.com>
    Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
    Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Without this fix, net-tools can not be compile with Linux kernel 4.8
and 4.9.

Change-Id: Iea47634822f471f5032bd7822f51735add209d91
Signed-off-by: Thao Nguyen <thao.nguyen.yb@rvc.renesas.com>
Signed-off-by: Takamitsu Honda <takamitsu.honda.pv@renesas.com>